# xCore, made by t.me/flxpr | tech.flink.gq/xcore

actionBars:
  global:
    noPermission: "&7У вас &cнедостаточно прав &7для выполнения данной команды"
    unknownCommand: "&cНеизвестная &7команда"
  core:
    reload: "&7Конфиг плагина &cперезагружен"
  motd:
    new: "&7Запись &cуспешно добавлена &7в конфиг"
    argNotProvided: "&7Запись для добавления &cне указана"

chat:
  core:
    help: "&ctech.flink.gq\n\n&c/core reload &8- &7перезагрузка конфига\n&c/core motd &8- &7добавление новой записи в список motd"
  broadcast:
    format: "&cОбъявление&7: %text% &7(Отправитель: &c%user%&7)" # %text% - текст объявления, %user% - отправитель

events:
  join: # вошедший пользователь - %user% (пр. "%user%, привет!"), tps - %tps%
    active: "disabled" # для выключения - disabled, включение - enabled
    title: "&7Привет, &c%user%&7!"
    subtitle: "&7Текущий TPS - &c%tps%"
  adminJoinEvent: # вошедший администратор - %user% (пр. "Администратор %user% зашел на сервер!")
    active: "enabled" # для выключения - disabled, включение - enabled
    sound: "achievement" # на выбор доступно 3 звука - achievement, exp, lightning
    title: "&7Администратор &c%user% &7зашел на сервер"

motd:
  active: "enabled"  # для выключения - disabled, включение - enabled
  list:
    - "&c│ &c&lXMINE &8▸ &7tech.flink.gq, thx &c☁\n&c│ &7Ванильный сервер майнкрафт &8▸ &7TPS: &c%tps%"
